.TH ft_readline 3 "13 April 2018" "" "42 Student Lib"
.SH NAME
libftreadline - Simple readline-alike lib for students
.SH SYNOPSYS
#include <libftreadline.h>

.nf
.I char *
.fi
.B ft_readline
(const char *prompt, t_rl_opts *opts);

.SH DESCRIPTION
libftreadline allows to get a line from the command line
with line-editing capabilities. It features termcaps compatibility
and still works when $TERM is undefined.
prompt may be NULL. In that case, no prompt is showed.
Cursor must be positionned at the beginning of the line.
Any other position is undefined behavior.

.SH RETURN VALUES
If EOF is catched,
.B ft_readline()
returns NULL. Otherwise, a valid C-string is passed. This string might be empty.
If no input has been typed,
.B ft_readline()
returns a valid C-string only containing the terminating NULL character.

.SH SEE ALSO
Nothing for now

.SH AUTHOR
Copyright kdumarai@ - 2017-2018 - Kelian DUMARAIS
